<?php

return [
    'login',
    'register',
    'help-center',
    'help-center/tickets',
    'help-center/manage',
    'mailbox/tickets',
    'mailbox/tickets/search',
    'admin/appearance',
    'admin/users',
    'admin/settings/authentication',
    'admin/settings/branding',
    'admin/settings/cache',
    'admin/settings/envato',
    'admin/settings/help-center',
    'admin/settings/permissions',
    'admin/settings/realtime',
    'admin/settings/ticketing',
    'admin/tags',
    'admin/triggers',
    'admin/triggers/new',
    'admin/groups',
    'admin/reports/conversations',
    'admin/reports/envato',
];
